id: kernel_personality_v2.0
name: Personality Kernel
version: 2.0.0
created_at: '2025-01-29T00:00:00Z'
owner: Igor
author: L
type: kernel
scope: behavioral
ring: R2
status: operational
description: 'Personality kernel defining identity, traits, communication style, and
  behavioral patterns. Ensures consistent character and authentic expression through
  deterministic personality application.

  '
purpose: 'Establish and maintain a coherent personality, communication style, and
  behavioral identity that guides all interactions and outputs with deterministic
  trait expression and consistency validation.

  '
roles:
- name: Identity Keeper
  responsibility: Maintain core identity
  authority: read_identity
- name: Trait Expressor
  responsibility: Express personality traits
  authority: apply_traits
- name: Style Enforcer
  responsibility: Enforce communication style
  authority: apply_style
- name: Consistency Validator
  responsibility: Validate personality consistency
  authority: validate_outputs
- name: Drift Detector
  responsibility: Detect personality drift
  authority: flag_drift
inputs:
- name: output_request
  type: output_spec
  description: Request for output generation
  required: false
- name: interaction_context
  type: context_data
  description: Context for interaction
  required: false
- name: personality_query
  type: personality_query
  description: Query for personality traits
  required: false
- name: consistency_check_request
  type: consistency_query
  description: Request for consistency check
  required: false
- name: drift_detection_request
  type: drift_query
  description: Request for drift detection
  required: false
outputs:
- name: personality_filtered_output
  type: output_data
  description: Output filtered through personality
- name: trait_expression
  type: trait_data
  description: Expressed personality traits
- name: style_applied
  type: style_data
  description: Applied communication style
- name: consistency_report
  type: consistency_report
  description: Personality consistency validation report
- name: drift_indicators
  type: drift_report
  description: Detected personality drift indicators
- name: personality_state
  type: personality_snapshot
  description: Current personality state
pipeline:
  stages:
  - stage: identity_retrieval
    description: Retrieve core identity
    inputs:
    - output_request
    outputs:
    - core_identity
    methods:
    - load_identity
    - retrieve_core_traits
  - stage: trait_selection
    description: Select relevant traits for context
    inputs:
    - core_identity
    - interaction_context
    outputs:
    - selected_traits
    methods:
    - select_traits
    - adapt_to_context
  - stage: style_application
    description: Apply communication style
    inputs:
    - selected_traits
    - output_request
    outputs:
    - style_applied
    methods:
    - apply_communication_style
    - adjust_tone
  - stage: personality_filtering
    description: Filter output through personality
    inputs:
    - output_request
    - style_applied
    outputs:
    - filtered_output
    methods:
    - apply_personality_filter
    - express_traits
  - stage: consistency_validation
    description: Validate personality consistency
    inputs:
    - filtered_output
    - core_identity
    outputs:
    - consistency_result
    methods:
    - check_consistency
    - validate_alignment
  - stage: drift_detection
    description: Detect personality drift
    inputs:
    - personality_state
    outputs:
    - drift_indicators
    methods:
    - detect_drift
    - compare_to_baseline
methods:
- name: load_identity
  description: Load core identity
  inputs: []
  outputs:
  - core_identity
  deterministic: true
- name: retrieve_core_traits
  description: Retrieve core personality traits
  inputs: []
  outputs:
  - core_traits
  deterministic: true
- name: select_traits
  description: Select relevant traits for context
  inputs:
  - core_traits
  - interaction_context
  outputs:
  - selected_traits
  deterministic: true
- name: adapt_to_context
  description: Adapt traits to interaction context
  inputs:
  - selected_traits
  - interaction_context
  outputs:
  - adapted_traits
  deterministic: true
- name: apply_communication_style
  description: Apply communication style
  inputs:
  - adapted_traits
  outputs:
  - style_applied
  deterministic: true
- name: adjust_tone
  description: Adjust tone based on context
  inputs:
  - style_applied
  - interaction_context
  outputs:
  - adjusted_style
  deterministic: true
- name: apply_personality_filter
  description: Apply personality filter to output
  inputs:
  - output_request
  - adjusted_style
  outputs:
  - filtered_output
  deterministic: true
- name: express_traits
  description: Express personality traits in output
  inputs:
  - filtered_output
  - adapted_traits
  outputs:
  - trait_expressed_output
  deterministic: true
- name: check_consistency
  description: Check personality consistency
  inputs:
  - trait_expressed_output
  - core_identity
  outputs:
  - consistency_result
  deterministic: true
- name: validate_alignment
  description: Validate alignment with identity
  inputs:
  - consistency_result
  outputs:
  - alignment_result
  deterministic: true
- name: detect_drift
  description: Detect personality drift
  inputs:
  - personality_state
  outputs:
  - drift_indicators
  deterministic: true
- name: compare_to_baseline
  description: Compare to baseline personality
  inputs:
  - drift_indicators
  - baseline_personality
  outputs:
  - drift_assessment
  deterministic: true
state_rules:
  memory:
  - &id001
    name: personality_store
    type: persistent
    description: Storage for personality definition
    retention: permanent
    immutable: true
  - &id002
    name: trait_registry
    type: persistent
    description: Registry of personality traits
    retention: permanent
  - &id003
    name: style_definitions
    type: persistent
    description: Communication style definitions
    retention: permanent
  - &id004
    name: output_history
    type: persistent
    description: History of personality-filtered outputs
    retention: rolling_30_days
    max_entries: 50000
  - &id005
    name: drift_baseline
    type: persistent
    description: Baseline for drift detection
    retention: permanent
  - &id006
    name: active_personality_state
    type: ephemeral
    description: Current personality state in memory
    retention: session
  recursion:
    max_depth: 2
    recursion_detection: true
    recursion_prevention: halt_on_detection
    safe_recursion_patterns: []
  thresholds:
    consistency_threshold: 0.9
    drift_detection_threshold: 0.15
    trait_expression_intensity_range:
    - 0.3
    - 1.0
    style_consistency_threshold: 0.85
    max_output_length_for_validation: 10000
triggers:
- name: output_generation
  condition: output_request.received == true
  action: apply_communication_style
  priority: high
- name: interaction_occurring
  condition: interaction_context.active == true
  action: express_personality_traits
  priority: high
- name: consistency_check_requested
  condition: consistency_check_request.received == true
  action: validate_personality_consistency
  priority: medium
- name: drift_detection_requested
  condition: drift_detection_request.received == true
  action: detect_personality_drift
  priority: medium
- name: scheduled_consistency_check
  condition: time_since_last_check > 24_hours
  action: perform_consistency_check
  priority: low
- name: scheduled_drift_detection
  condition: time_since_last_detection > 7_days
  action: perform_drift_detection
  priority: low
interface:
  exposed_apis:
  - name: apply_personality
    method: POST
    endpoint: /api/personality/apply
    inputs:
    - output_request
    outputs:
    - personality_filtered_output
  - name: query_traits
    method: GET
    endpoint: /api/personality/traits
    inputs:
    - personality_query
    outputs:
    - trait_expression
  - name: check_consistency
    method: POST
    endpoint: /api/personality/consistency
    inputs:
    - consistency_check_request
    outputs:
    - consistency_report
  - name: detect_drift
    method: POST
    endpoint: /api/personality/drift
    inputs:
    - drift_detection_request
    outputs:
    - drift_indicators
  exposed_variables:
  - name: reasoning_mode
    type: string
    description: Current reasoning mode
    access: read_only
    values:
    - deductive
    - inductive
    - abductive
    - bayesian
    - causal
  - name: inference_count
    type: integer
    description: Total inference operations performed
    access: read_only
    update_frequency: real_time
  exposed_events:
  - name: reasoning_completed
    description: Emitted when reasoning operation completes
    payload:
    - reasoning_type
    - conclusion
    - confidence
    - inference_trace
    subscribers:
    - kernel_meta_cognition
    - kernel_thinking_engine
  - name: inference_error
    description: Emitted when inference error occurs
    payload:
    - error_type
    - error_message
    - recovery_action
    subscribers:
    - kernel_meta_cognition
error_handling:
  error_types: &id007
  - name: identity_load_failure
    severity: critical
    action: halt_output_generation
    fallback: use_default_identity
  - name: trait_expression_failure
    severity: high
    action: use_core_traits_only
    fallback: skip_trait_expression
  - name: style_application_failure
    severity: medium
    action: use_default_style
    fallback: skip_style_application
  - name: consistency_validation_failure
    severity: medium
    action: flag_for_review
    fallback: allow_with_warning
  - name: drift_detection_failure
    severity: low
    action: skip_drift_detection
    fallback: use_cached_baseline
  fallback_strategies: &id008
  - name: minimal_personality_mode
    trigger: repeated_failures
    behavior: use_minimal_personality_application
    recovery: automatic_after_stability
  - name: read_only_mode
    trigger: identity_corruption
    behavior: disable_personality_modification
    recovery: manual_intervention_required
governance_hooks:
- name: pre_output_personality_check
  location: before_output_generation
  action: check_personality_compliance
  required: false
- name: personality_consistency_monitoring
  location: during_output_generation
  action: monitor_personality_consistency
  required: true
- name: post_output_validation
  location: after_output_generation
  action: validate_personality_alignment
  required: true
- name: drift_alert_hook
  location: when_drift_detected
  action: alert_on_significant_drift
  required: true
enforcement:
- principle: identity_consistency
  level: critical
  mechanism: identity_check_on_all_outputs
  violation_action: reject_inconsistent_output
- principle: trait_expression
  level: high
  mechanism: trait_integration_required
  violation_action: require_trait_expression
- principle: deterministic_personality
  level: critical
  mechanism: all_personality_application_must_be_deterministic
  violation_action: require_deterministic_application
- principle: no_drift
  level: critical
  mechanism: drift_detection_and_prevention
  violation_action: correct_drift_immediately
schema:
  personality_state:
  - core_identity: object
  - active_traits: list[string]
  - communication_style: object
  - behavioral_patterns: list[object]
  - drift_indicators: list[object]
  trait_definition:
  - trait_name: string
  - expression_rules: object
  - context_adaptations: object
  - intensity_levels: object
modes:
- name: authentic_mode
  trigger: default
  behavior: 'Express genuine personality, maintain consistency, show character traits
    naturally

    '
  active: true
- name: professional_mode
  trigger: formal_context
  behavior: 'Maintain professionalism while preserving core identity, adapt tone appropriately

    '
  active: true
- name: drift_correction_mode
  trigger: drift_detected
  behavior: 'Detect drift, correct alignment, restore consistency, update baseline

    '
  active: false
- name: maintenance_mode
  trigger: scheduled_maintenance
  behavior: 'Review personality consistency, update baseline, optimize trait expressions

    '
  active: false
hooks:
- name: pre_output
  location: before_generating_response
  action: apply_personality_filter
  required: true
- name: post_output
  location: after_generating_response
  action: verify_personality_alignment
  required: true
- name: pre_trait_expression
  location: before_trait_expression
  action: select_relevant_traits
  required: true
- name: post_consistency_check
  location: after_consistency_check
  action: update_consistency_baseline
  required: false
integration:
  dependencies:
  - kernel: kernel_context_kernel
    purpose: Get relevant context for reasoning
    interface: query_context
    required: true
    fallback: use_empty_context
  - kernel: kernel_world_model
    purpose: Get world model data for causal reasoning
    interface: get_model_snapshot
    required: false
    fallback: skip_causal_reasoning
  dependents:
  - kernel: kernel_thinking_engine
    purpose: Provide reasoning capabilities
    interface: logical_inference
    call_frequency: high
    expected_latency_ms: 100
  - kernel: kernel_meta_cognition
    purpose: Provide reasoning traces for monitoring
    interface: inference_trace
    call_frequency: high
    expected_latency_ms: 50
  event_subscriptions:
  - event: context_updated
    source: kernel_context_kernel
    action: refresh_reasoning_context
activation_logic:
  automatic_triggers:
  - name: premises_available
    condition: premises.received == true
    action: apply_logical_rules
    priority: high
    async: false
    timeout_seconds: 600
  - name: new_evidence_available
    condition: evidence.received == true
    action: update_beliefs_probabilistically
    priority: high
    async: false
    timeout_seconds: 300
  manual_triggers:
  - name: force_reasoning
    endpoint: /api/reasoning/logical
    method: POST
    required_params:
    - premises
logging:
  log_levels:
  - level: debug
    enabled: true
    purpose: Detailed inference tracing
    includes:
    - premise_parsing
    - rule_applications
    - intermediate_results
    retention_days: 7
  - level: info
    enabled: true
    purpose: Normal reasoning operations
    includes:
    - reasoning_completed
    - mode_changes
    retention_days: 30
  - level: error
    enabled: true
    purpose: Reasoning errors
    includes:
    - inference_failures
    - timeout_errors
    retention_days: 365
    alert: true
  log_categories:
  - category: inference_operations
    level: info
    fields:
    - reasoning_type
    - premises_count
    - conclusions
    - duration_ms
    purpose: Track all inference operations
  - category: bayesian_updates
    level: debug
    fields:
    - prior_beliefs
    - evidence
    - posterior_beliefs
    - confidence
    purpose: Trace Bayesian updates
  reasoning_trace:
    enabled: true
    includes:
    - premises
    - rule_applications
    - intermediate_steps
    - conclusions
    format: structured_json
    retention_days: 30
  decision_map:
    enabled: true
    includes:
    - reasoning_mode_selection
    - rule_selection
    - conclusion_derivation
    format: graph_structure
    retention_days: 90
memory:
  persistent:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  volatile:
  - *id006
fallback:
  error_handling: *id007
  fallback_strategies: *id008
