"""
L9 Core Schemas Module

Generated by L9_MASTER_SCHEMA_EXTRACTOR v3.0
Aligned with Memory.yaml v1.0.1

Source schemas:
  - Memory.yaml v1.0.1 (PacketEnvelope, aligned_with_repo)
  - research_factory_schema.yaml (5-pass pipeline)
  - capabilities.py (Security - Agent Capabilities)
  - event_stream.py (Security - Event Stream Types)

All models are Pydantic v2 compliant with strict validation.
"""

from core.schemas.packet_envelope import (
    PacketEnvelope,
    PacketEnvelopeIn,
    PacketWriteResult,
    PacketMetadata,
    PacketProvenance,
    PacketConfidence,
    SemanticSearchRequest,
    SemanticHit,
    SemanticSearchResult,
)

# Security Schemas
from core.schemas.capabilities import (
    ToolName,
    Capability,
    AgentCapabilities,
    DEFAULT_READER_CAPABILITIES,
    DEFAULT_CODER_CAPABILITIES,
    DEFAULT_ARCHITECT_CAPABILITIES,
)

from core.schemas.event_stream import (
    HandshakeStatus,
    SecurityEventType,
    AgentHandshake,
    HandshakeResponse,
    SecurityEvent,
    CapabilityViolation,
    create_handshake_event,
    create_violation_event,
)

from core.schemas.research_factory_models import (
    ResearchJobSpec,
    Query,
    QueryPlan,
    Superprompt,
    RetrievalBatch,
    ParsedObject,
    ValidationStatus,
    IntegrationResult,
    ResearchMetrics,
)

from core.schemas.research_factory_state import (
    ResearchState,
    PassStatus,
)

# WebSocket Event Stream
from core.schemas.ws_event_stream import (
    EventType,
    EventMessage,
    AgentHeartbeat,
    ErrorEvent,
)

# Task Types (Phase 2.5)
from core.schemas.tasks import (
    TaskStatus,
    TaskKind,
    AgentTask,
    TaskResult,
    TaskEnvelope,
    TaskGraph,
    TaskBatch,
)

from core.schemas.research_factory_nodes import (
    pass_1_plan_queries,
    pass_2_build_superprompts,
    pass_3_execute_retrieval,
    pass_4_extract_results,
    pass_5_integrate_results,
)

__all__ = [
    # Packet Envelope (Memory.yaml v1.0.1)
    "PacketEnvelope",
    "PacketEnvelopeIn",
    "PacketWriteResult",
    "PacketMetadata",
    "PacketProvenance",
    "PacketConfidence",
    "SemanticSearchRequest",
    "SemanticHit",
    "SemanticSearchResult",
    # Research Factory Models
    "ResearchJobSpec",
    "Query",
    "QueryPlan",
    "Superprompt",
    "RetrievalBatch",
    "ParsedObject",
    "ValidationStatus",
    "IntegrationResult",
    "ResearchMetrics",
    # Research Factory State
    "ResearchState",
    "PassStatus",
    # Research Factory Nodes
    "pass_1_plan_queries",
    "pass_2_build_superprompts",
    "pass_3_execute_retrieval",
    "pass_4_extract_results",
    "pass_5_integrate_results",
    # Security - Capabilities
    "ToolName",
    "Capability",
    "AgentCapabilities",
    "DEFAULT_READER_CAPABILITIES",
    "DEFAULT_CODER_CAPABILITIES",
    "DEFAULT_ARCHITECT_CAPABILITIES",
    # Security - Event Stream
    "HandshakeStatus",
    "SecurityEventType",
    "AgentHandshake",
    "HandshakeResponse",
    "SecurityEvent",
    "CapabilityViolation",
    "create_handshake_event",
    "create_violation_event",
    # WebSocket Event Stream
    "EventType",
    "EventMessage",
    "AgentHeartbeat",
    "ErrorEvent",
    # Task Types (Phase 2.5)
    "TaskStatus",
    "TaskKind",
    "AgentTask",
    "TaskResult",
    "TaskEnvelope",
    "TaskGraph",
    "TaskBatch",
]
