"""
L9 Universal Schema Aggregator

Generated by L9_MASTER_SCHEMA_EXTRACTOR v3.0
Aligned with Memory.yaml v1.0.1

This module re-exports all L9 core schemas for convenient access.
Import from here for the complete schema set.

Usage:
    from core.schemas.universal_schema import (
        PacketEnvelope,
        ResearchJobSpec,
        ResearchState,
    )
"""

# =============================================================================
# Packet Envelope (Memory.yaml v1.0.1)
# =============================================================================

from core.schemas.packet_envelope import (
    PacketConfidence,
    PacketEnvelope,
    PacketEnvelopeIn,
    PacketMetadata,
    PacketProvenance,
    PacketWriteResult,
    SemanticHit,
    SemanticSearchRequest,
    SemanticSearchResult,
)

# =============================================================================
# Research Factory Models (research_factory_schema.yaml)
# =============================================================================

from core.schemas.research_factory_models import (
    IntegrationResult,
    ParsedObject,
    Query,
    QueryPlan,
    ResearchJobSpec,
    ResearchMetrics,
    RetrievalBatch,
    Superprompt,
    ValidationStatus,
)

# =============================================================================
# Research Factory State
# =============================================================================

from core.schemas.research_factory_state import (
    PassMetadata,
    PassStatus,
    ResearchState,
)

# =============================================================================
# Research Factory Nodes
# =============================================================================

from core.schemas.research_factory_nodes import (
    build_research_graph,
    pass_1_plan_queries,
    pass_2_build_superprompts,
    pass_3_execute_retrieval,
    pass_4_extract_results,
    pass_5_integrate_results,
)

# =============================================================================
# Public API
# =============================================================================

__all__ = [
    # === Packet Envelope (Memory.yaml v1.0.1) ===
    "PacketEnvelope",
    "PacketEnvelopeIn",
    "PacketWriteResult",
    "PacketMetadata",
    "PacketProvenance",
    "PacketConfidence",
    "SemanticSearchRequest",
    "SemanticHit",
    "SemanticSearchResult",
    # === Research Factory Models ===
    "ResearchJobSpec",
    "Query",
    "QueryPlan",
    "Superprompt",
    "RetrievalBatch",
    "ParsedObject",
    "ValidationStatus",
    "IntegrationResult",
    "ResearchMetrics",
    # === Research Factory State ===
    "ResearchState",
    "PassStatus",
    "PassMetadata",
    # === Research Factory Nodes ===
    "pass_1_plan_queries",
    "pass_2_build_superprompts",
    "pass_3_execute_retrieval",
    "pass_4_extract_results",
    "pass_5_integrate_results",
    "build_research_graph",
]


# =============================================================================
# Schema Version Info
# =============================================================================

SCHEMA_VERSION = "1.0.1"
MODULE_VERSION = "1.0.0"
GENERATED_BY = "L9_MASTER_SCHEMA_EXTRACTOR v3.0"
SOURCE_SCHEMAS = [
    "Memory.yaml (packet_envelope.v1.0.1, aligned_with_repo)",
    "research_factory_schema.yaml (research_factory.v1.0.0)",
]


def get_schema_info() -> dict:
    """Return schema version information."""
    return {
        "schema_version": SCHEMA_VERSION,
        "module_version": MODULE_VERSION,
        "generated_by": GENERATED_BY,
        "source_schemas": SOURCE_SCHEMAS,
        "total_models": len(__all__),
    }
