# ============================================================
# L9 MEMORY MODULE — CANONICAL SPEC v2.0
# ============================================================
#
# PURPOSE
#   Declarative source of truth for the L9 persistent memory system.
#   This YAML DESCRIBES memory — it does not replace Python logic.
#
# GUARANTEES
#   - Non-destructive: no existing files are overwritten
#   - Binding-only: Cursor must wire this into existing modules
#   - Persistent-agent compatible (NO session handoffs)
#
# SCOPE
#   Applies to:
#     memory/
#       checkpoint_manager.py
#       ingestion.py
#       retrieval.py
#       insight_extraction.py
#       substrate_*.py
#
# ============================================================

schema:
  name: l9-memory
  version: 2.0
  mode: persistent-agent
  mutation_policy: bind_only

memory_layers:

  semantic:
    backend: postgres_pgvector
    module: substrate_semantic.py
    responsibilities:
      - embedding_storage
      - semantic_recall
      - similarity_ranking
    embedding:
      models:
        primary: text-embedding-3-small
      lifecycle:
        compute: async
        refresh_policy: stale_on_schema_change
        prune_policy: low_value_ttl

  structural:
    backend: neo4j
    module: substrate_graph.py
    responsibilities:
      - entity_graph
      - relationship_traversal
      - event_timeline
    node_types:
      - User
      - Agent
      - Session
      - Message
      - Entity
      - Event
      - HyperEvent

  state:
    backend: postgres
    module: state_manager.py
    responsibilities:
      - agent_state
      - long_term_flags
      - contradiction_tracking

pipelines:

  ingestion:
    entrypoint: ingestion.py
    stages:
      - normalize_input
      - persist_message
      - enqueue_embedding
      - enqueue_graph_sync

  extraction:
    entrypoint: insight_extraction.py
    outputs:
      - entities
      - topics
      - decisions
      - facts
    binding:
      graph: substrate_graph.py
      state: state_manager.py

  retrieval:
    entrypoint: retrieval.py
    bundle:
      recent:
        source: postgres
        limit: 20
      semantic_hits:
        source: pgvector
        k: 10
      graph_context:
        source: neo4j
        depth: 2
      facts:
        source: state_manager

persistence_rules:
  no_session_reset: true
  overwrite_existing_records: false
  idempotent_writes: true

validation:
  required_modules_exist: true
  forbid_duplicate_memory_stacks: true
  canonical_path: memory/

# ============================================================
# END MEMORY SPEC
# ============================================================
